### ISSUE TITLE
Changer l'avatar par défaut sur l'instance

### ISSUE THREAD

**Issue by Dehelssey** [Cl0v1s/mangane-ui#17]
Pour l'avatar par défaut je verrai bien juste un seul grain de raisin emoji plutôt que le favicon (croppé qui plus est)

**Comment by Cl0v1s** [comment]
+1, en revanche je ne sais pas si je peux soliciter Morgane encore une fois

**Comment by Dehelssey** [comment]
Je t'extraie ça depuis ma version vectorisée !

**Comment by Dehelssey** [comment]
en vrai le favicon carré que je t'ai fait en #18 ça devrait le faire non ?

**Comment by Dehelssey** [comment]
tu m'as assigned mais je dois te faire quoi ? ^^

**Comment by Cl0v1s** [comment]
Je suis stupide, j'ai lu trop vite, la ressource est déjà là. Merci ! Haha

**Comment by Cl0v1s** [comment]
Changé dans les paramètres de l'instance
