### ISSUE TITLE
Update icones fils locaux et fédérés

### ISSUE THREAD

**Issue by Dehelssey** [Cl0v1s/mangane-ui#18]
L'icône du **fil fédéré** est beaucoup plus "grasse" que les autres. 

plusieurs options :
- garder ce logo en affinant le trait
- opter pour une version alternative du logo du fediverse ¹
- opter pour une icone plus "universelle" et non purement fediverse

¹ cf [cette publi](https://activism.openworlds.info/@dsfgs/107719222939397800)
![image](https://user-images.githubusercontent.com/20315413/166151380-b9c2a97c-2119-43d1-b919-4b0b2f3aa201.png)

Pour l'icône du **fil local**, peut-être une déclinaison linéaire du logo grappe serait peut-être plus logique.

**Comment by Dehelssey** [comment]
je m'occupe de te faire tes propales graphiques. SVG ?

**Comment by Cl0v1s** [comment]
Je veux bien, merci !

**Comment by Dehelssey** [comment]
![logo-redux](https://user-images.githubusercontent.com/20315413/167165209-0125356b-033b-437b-84c3-1d7425cf2b4e.svg)
![logo-redux-linear](https://user-images.githubusercontent.com/20315413/167165214-b7f373d0-d118-475d-bc32-1d3d884d4269.svg)

pour le fil local !

pour le fil fédéré j'étais parti sur une icone de globe, faut juste que je trouve fasse une version pleine en plus de la linéaire pour quand le fil est actif

**Comment by Dehelssey** [comment]
![discover](https://user-images.githubusercontent.com/20315413/168606423-d2d4c205-9d38-4abb-9401-249aeb35e6a9.svg)

**Comment by Cl0v1s** [comment]
C'est pas génant que l'épaisseur du trait SVG soit pas la même ?

**Comment by Dehelssey** [comment]
Normalement à l'échelle c'était la même épaisseur...

De toutes façons avec la future update de l'UI à venir ça doit encore changer les icones je crois...

**Comment by Cl0v1s** [comment]
Non non, je les ai utilisées dans la nouvelle UI et ça passe très bien ! 

Parfait si c'est la même épaisseur a l'échelle, je vais l'utiliser !

Le 30 juillet 2022 22:07:41 GMT+02:00, "Guérin" ***@***.***> a écrit :
