### ISSUE TITLE
Logo du site en SVG

### ISSUE THREAD

**Issue by Dehelssey** [Cl0v1s/mangane-ui#20]
Actuellement le logo du site est un PNG de 1200px de haut ça me parait pas super opti :stuck_out_tongue_winking_eye: 

il faudrait un SVG, idéalement dans un format carré :+1:

**Comment by Cl0v1s** [comment]
Je vais voir ce que je peux faire, mais Mog ne fait pas de vectoriel, et les outils de conversion ne sont pas toujours très opti...

**Comment by Dehelssey** [comment]
Je l'ai vectorisé sur mon Figma ! je suis con j'ai oublié de te le partager !

![logo-spring](https://user-images.githubusercontent.com/20315413/167165218-6c90712e-164a-46c2-8f3a-059fa6a29cab.svg)

**Comment by Cl0v1s** [comment]
Hoplah c'est fait (pas besoin de code, juste du paramétrage)
