### ISSUE TITLE
Aucun moyen d'accéder à la liste des MP

### ISSUE THREAD

**Issue by Dehelssey** [Cl0v1s/mangane-ui#21]
Il n'y nulle part dans l'UI un accès aux MP. Pourtant quand on en envoie un il s'affiche dans une TL dédiée à l'URL suivante https://bdx.town/messages

Faudrait rajouter un ptit lien non ?

Idéalement faudrait même merger chats et MP mais j'sais pas trop comment faire...

**Comment by Cl0v1s** [comment]
Alors Merger MP et Chats c'est un gros boulot avec bcp de repercussions. 

Par contre pour les messages, je te suis. Tu verrais ça ou ?

**Comment by Dehelssey** [comment]
sur desktop je t'aurais bien dit dans la sidebar à la place des chats justement vu qu'on a déjà les chats en bas à droite de l'écran
![image](https://user-images.githubusercontent.com/20315413/168150795-8cf053f9-22bb-402d-a33e-46a449a1581b.png)

mais comme sur mobile je pensais les mettre dans le sous-menu, ça serait plus simple techniquement qu'ils soient ici : 
![image](https://user-images.githubusercontent.com/20315413/168150910-98852d42-2605-4fb1-a79e-11cb0861b184.png)
vu que c'est ce menu là qui finit dans le sous-menu mobile.
![image](https://user-images.githubusercontent.com/20315413/168151357-1a296f09-8070-4219-9298-a3bf6f8f60fb.png)


Je checke sur la prochaine version aussi pour pas te faire faire deux fois le taf.

dans la future UI ça donne ça : 
![image](https://user-images.githubusercontent.com/20315413/168151115-de5bc6ac-be59-4413-8e1f-04b76718122b.png)

donc on peut clairement les foutre dans "more" sur desktop (et donc dans le menu déroulant sur mobile) 
![image](https://user-images.githubusercontent.com/20315413/168151256-2366e0fd-6a0f-400b-9da1-e020adff4c65.png)
