### ISSUE TITLE
Bug contenu onboarding

### ISSUE THREAD

**Issue by Dehelssey** [Cl0v1s/mangane-ui#32]
Sur mon tél l'onboarding fait des siennes :
![Screenshot_2022-08-21-17-40-17-124_com vivaldi browser](https://user-images.githubusercontent.com/20315413/185806630-2ddaedb0-f301-4bce-8a21-0296bf339682.jpg)

**Comment by Dehelssey** [comment]
OK c'est parce que mangane n'était pas en Français donc pas de trad fournie >_<

**Comment by Cl0v1s** [comment]
Duplicate https://github.com/Cl0v1s/mangane-ui/issues/29
