### ISSUE TITLE
Ajouter un mockup au readme

### ISSUE THREAD

**Issue by Dehelssey** [Cl0v1s/mangane-ui#34]
Comme promis voici des petits mockups pour le readme du projet ! 

![dark mode](https://user-images.githubusercontent.com/20315413/186252812-2dfdc8de-61e5-492a-bb6e-ca843c06b5f3.png)
![light mode](https://user-images.githubusercontent.com/20315413/186252816-b27e90f1-8f9a-4d13-977c-fb26630b730d.png)
![duo mode](https://user-images.githubusercontent.com/20315413/186252814-91297d29-b052-4ca5-b0d2-c2cb33ad71b9.png)

**Comment by Cl0v1s** [comment]
Superbe travail ! J'ajoute ça de suite !
