### ISSUE TITLE
La colonne latérale change de côté d'une vue à l'autre

### ISSUE THREAD

**Issue by Dehelssey** [Cl0v1s/mangane-ui#8]
sur la vue "Home" (et sur l'ensemble des fils) on est passés en deux colonnes avec une seule colonne latérale, à gauche (évidemment)
![image](https://user-images.githubusercontent.com/20315413/141973826-374702ae-0bc5-4bf8-96da-ea07d9df4e69.png)

sur les vues Notifications, Modifier le profil, Demandes de suivi, Bookmarks, Listes, Sécurité & Préférences en revanche on repasse à droite (la colonne de gauche étant elle vide)

![image](https://user-images.githubusercontent.com/20315413/141973705-11955400-964a-4bb4-9bb5-6f94c3811f58.png)

**Comment by Cl0v1s** [comment]
Plus d'actualité suite à nouvelle UI
