### ISSUE TITLE
Onboarding 

### ISSUE THREAD

**Issue by Cl0v1s** [Cl0v1s/mangane-ui#9]
# Objectif 

Développer un onboarding pour accueillir les nouveaux membres

5 écrans.

## Ecran handle 
Écran explication handle @pseudo@instance basé sur l'image des e-mails présentant une illustration (à déterminer)

_Introduction du terme ancre (handle)._ 

### _Schématisation de l’illustration_
![1](https://bdx.town/media/fda42682e80d1c3d380363e0fa53c426ae7cee1659f52d0e33bd05ff79c46cee.jpg)

## Ecran fils 
Écran explication fils (personnel, local, découvrir) présentant une illustration (à déterminer)

### _Schématisation de l’illustration_
![2](https://bdx.town/media/4aa03a3fa21534f2d88621b33d81e7afcf3987a1f9411f9203a6d2ec54629b0e.jpg)

## Ecran confidentialité 
Écran présentant les options de confidentialité présentant des captures d'écran / reprenant les icônes 

![image](https://user-images.githubusercontent.com/917518/163675758-f7356390-1280-430f-a6ac-8de580fb8fd6.png)

Proposition de verbatim: 

_* Public: le toot est visible sur l'ensemble des fils, et aux autres instances. 
* Non-listé: Il faut avoir le lien du toot pour le voir
* Abonné.e.s seulement: le toot est visible uniquement pour les personnes qui vous suivent 
* Direct: le toot n'est visible qu'aux personnes mentionnées à l'aide de leur ancre_

## Ecran _"Quoi faire ensuite"_

* Invite à consulter https://joinfediverse.wiki/Getting_started_with_your_Fediverse_account/fr
* Parler des hashtags
* Écran de suggestion de suivi, basé sur https://communitywiki.org/trunk/
* Met également en avant le compte https://bdx.town/@feditips@mstdn.social

# Ressources

https://bdx.town/@clovis/posts/AIQqGdljbqD5ruAjrc

https://guerin.notion.site/BDX-town-2047767a47764afe8c3bda67b933d9a9

**Comment by Dehelssey** [comment]
Du coup à la création du compte après l'onboarding ça me paraît plus logique pour l'utilisateur·ice d'arriver sur sa "home" en version placeholder / vide avec un bouton vers l'annuaire pour inciter à suivre des gens ?

Pour info actuellement tu es follow par défaut donc y'a un flux avec que toi c'est ptet un peu sauvage ^^

Si on t'unfollowe ça donne ça : 
![image](https://user-images.githubusercontent.com/20315413/166711273-c1561cbd-0077-4cb8-b048-486f60973098.png)

un peu austère^^

**Comment by Cl0v1s** [comment]
Oui je me suis unfoillow automatiquement, ça portait à confusion. C'était pour que je puisse savoir quand un nouveau membre arrive, mais mnt j'au une alerte mail
